# Site settings
name: 爱的发射点
email: ichangjian@163.com
author: XXXX
url: http://www.hifreud.com
resume_site: https://www.linkedin.com/in/inchangjian/
github: https://github.com/ichangjian/
baseurl: ""
description: Actually, less is more!
meta_description: my blog
# motto: It's our wits that make us men.
# banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ichangjian

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

